#!/usr/bin/env python3
"""Generate byte-exact C fixtures from the pinned AEXB/AEXT transport corpus."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = (HERE / "fixtures" / "anti_exfil" / "transport" /
          "protocol-v1-multislot-vectors.json")
OUTPUT = HERE / "anti_exfil_transport_vectors.generated.h"
SOURCE_SHA256 = "bafd399a342e1be965666d4efca970b50218a2fb2e2820c418ad64686bac1bb3"


def c_array(name: str, value: bytes) -> str:
    lines = [f"static const uint8_t {name}[] = {{"]
    for offset in range(0, len(value), 12):
        chunk = value[offset:offset + 12]
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def render() -> str:
    raw = SOURCE.read_bytes()
    actual = hashlib.sha256(raw).hexdigest()
    if actual != SOURCE_SHA256:
        raise ValueError(f"transport corpus: expected SHA-256 {SOURCE_SHA256}, got {actual}")
    corpus = json.loads(raw)
    if corpus["ur_type"] != "x-btc-anti-exfil" or corpus["network_code"] != 4:
        raise ValueError("transport profile identity changed")

    out = [
        "/* Generated by generate_anti_exfil_transport_fixtures.py; do not edit. */",
        "#ifndef KERN_ANTI_EXFIL_TRANSPORT_VECTORS_GENERATED_H",
        "#define KERN_ANTI_EXFIL_TRANSPORT_VECTORS_GENERATED_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f'#define ANTI_EXFIL_TRANSPORT_SOURCE_SHA256 "{SOURCE_SHA256}"',
    ]
    entries = []
    maximum_lengths = {"message": 0, "package": 0, "cbor": 0}
    for index, item in enumerate(corpus["messages"]):
        message = bytes.fromhex(item["message_hex"])
        package = bytes.fromhex(item["package_hex"])
        cbor = bytes.fromhex(item["canonical_cbor_hex"])
        if len(message) != item["message_length"] or len(package) != item["package_length"]:
            raise ValueError(f"{item['name']}: length metadata mismatch")
        if hashlib.sha256(message).hexdigest() != item["message_sha256"]:
            raise ValueError(f"{item['name']}: message digest mismatch")
        if hashlib.sha256(package).hexdigest() != item["package_sha256"]:
            raise ValueError(f"{item['name']}: package digest mismatch")
        maximum_lengths["message"] = max(maximum_lengths["message"], len(message))
        maximum_lengths["package"] = max(maximum_lengths["package"], len(package))
        maximum_lengths["cbor"] = max(maximum_lengths["cbor"], len(cbor))
        for suffix, value in (("MESSAGE", message), ("PACKAGE", package), ("CBOR", cbor)):
            out.extend([c_array(f"ANTI_EXFIL_TRANSPORT_{suffix}_{index}", value), ""])
        out.append(f"static const char *const ANTI_EXFIL_TRANSPORT_UR_PARTS_{index}[] = {{")
        out.extend(f'    "{part}",' for part in item["medium_ur_parts"])
        out.extend(["};", ""])
        entries.append((index, item["stage"]))

    out[8:8] = [
        f"#define ANTI_EXFIL_TRANSPORT_MAX_MESSAGE_LEN {maximum_lengths['message']}u",
        f"#define ANTI_EXFIL_TRANSPORT_MAX_PACKAGE_LEN {maximum_lengths['package']}u",
        f"#define ANTI_EXFIL_TRANSPORT_MAX_CBOR_LEN {maximum_lengths['cbor']}u",
        "",
    ]

    out.extend([
        "typedef struct {",
        "  const uint8_t *message;",
        "  size_t message_len;",
        "  const uint8_t *package;",
        "  size_t package_len;",
        "  const uint8_t *cbor;",
        "  size_t cbor_len;",
        "  const char *const *ur_parts;",
        "  size_t ur_part_count;",
        "  uint8_t stage;",
        "} anti_exfil_transport_fixture_t;",
        "",
        "static const anti_exfil_transport_fixture_t ANTI_EXFIL_TRANSPORT_FIXTURES[] = {",
    ])
    for index, stage in entries:
        out.extend([
            "  {",
            f"    .message = ANTI_EXFIL_TRANSPORT_MESSAGE_{index},",
            f"    .message_len = sizeof(ANTI_EXFIL_TRANSPORT_MESSAGE_{index}),",
            f"    .package = ANTI_EXFIL_TRANSPORT_PACKAGE_{index},",
            f"    .package_len = sizeof(ANTI_EXFIL_TRANSPORT_PACKAGE_{index}),",
            f"    .cbor = ANTI_EXFIL_TRANSPORT_CBOR_{index},",
            f"    .cbor_len = sizeof(ANTI_EXFIL_TRANSPORT_CBOR_{index}),",
            f"    .ur_parts = ANTI_EXFIL_TRANSPORT_UR_PARTS_{index},",
            f"    .ur_part_count = sizeof(ANTI_EXFIL_TRANSPORT_UR_PARTS_{index}) / sizeof(ANTI_EXFIL_TRANSPORT_UR_PARTS_{index}[0]),",
            f"    .stage = {stage},",
            "  },",
        ])
    out.extend([
        "};",
        "",
        "#endif // KERN_ANTI_EXFIL_TRANSPORT_VECTORS_GENERATED_H",
        "",
    ])
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("generated anti-exfil transport fixtures are stale")
    else:
        OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
