#!/usr/bin/env python3
"""Generate on-device known-answer tests for SLH-DSA-SHA2-128s.

slhdsa-c ships no vector files; its own test harness downloads NIST ACVP
vectors at test time and shells out to a CLI binary per case. Kern needs them
baked into the firmware instead, so this pulls the ACVP vectors once and emits
main/bench/kat_slhdsa_sha2_128s.h.

Run it only to refresh the vectors; the generated header is committed.

    python3 scripts/gen_slhdsa_kat.py
"""

import json
import sys
import urllib.request
from pathlib import Path

ACVP_BASE = (
    "https://raw.githubusercontent.com/usnistgov/ACVP-Server/"
    "v1.1.0.40/gen-val/json-files"
)
PARAM_SET = "SLH-DSA-SHA2-128s"
OUT = Path(__file__).resolve().parent.parent / "main/bench/kat_slhdsa_sha2_128s.h"

# One case per entry point. More would only lengthen the boot gate; these cover
# both signing APIs and the keygen path. Within a group the shortest-message
# case is chosen -- message length has no bearing on what is being validated,
# and ACVP messages run to 8 KB, which would bloat the generated header.
KEYGEN_CASES = 2
SIGN_CASES = 1


def fetch(path):
    url = f"{ACVP_BASE}/{path}"
    print(f"fetching {url}", file=sys.stderr)
    with urllib.request.urlopen(url, timeout=300) as r:
        return json.load(r)


def results_by_tcid(doc):
    out = {}
    for group in doc["testGroups"]:
        for test in group["tests"]:
            out[test["tcId"]] = test
    return out


def pick_group(doc, **match):
    for group in doc["testGroups"]:
        if group.get("parameterSet") != PARAM_SET:
            continue
        if all(group.get(k) == v for k, v in match.items()):
            return group
    raise SystemExit(f"no {PARAM_SET} group matching {match}")


def c_bytes(name, hexstr):
    data = bytes.fromhex(hexstr)
    lines = []
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
        lines.append(f"    {chunk},")
    body = "\n".join(lines)
    return f"static const uint8_t {name}[{len(data)}] = {{\n{body}\n}};\n"


def main():
    keygen_prompt = fetch("SLH-DSA-keyGen-FIPS205/prompt.json")
    keygen_expected = results_by_tcid(fetch("SLH-DSA-keyGen-FIPS205/expectedResults.json"))
    siggen_prompt = fetch("SLH-DSA-sigGen-FIPS205/prompt.json")
    siggen_expected = results_by_tcid(fetch("SLH-DSA-sigGen-FIPS205/expectedResults.json"))

    parts = []
    parts.append(
        "/* Generated by scripts/gen_slhdsa_kat.py -- do not edit.\n"
        " *\n"
        f" * NIST ACVP known-answer tests for {PARAM_SET}, from\n"
        " * usnistgov/ACVP-Server v1.1.0.40. Deterministic cases only\n"
        " * (addrnd = NULL), so every run must reproduce these bytes exactly.\n"
        " */\n"
        "\n"
        "#ifndef KAT_SLHDSA_SHA2_128S_H\n"
        "#define KAT_SLHDSA_SHA2_128S_H\n"
        "\n"
        "#include <stdint.h>\n"
        "\n"
        "// clang-format off\n"
    )

    # --- keygen -------------------------------------------------------------
    kg = pick_group(keygen_prompt, testType="AFT")
    chosen = kg["tests"][:KEYGEN_CASES]
    parts.append(f"\n#define KAT_KEYGEN_COUNT {len(chosen)}\n\n")
    for i, t in enumerate(chosen):
        exp = keygen_expected[t["tcId"]]
        parts.append(f"/* keyGen tcId {t['tcId']} */\n")
        parts.append(c_bytes(f"kat_kg{i}_sk_seed", t["skSeed"]))
        parts.append(c_bytes(f"kat_kg{i}_sk_prf", t["skPrf"]))
        parts.append(c_bytes(f"kat_kg{i}_pk_seed", t["pkSeed"]))
        parts.append(c_bytes(f"kat_kg{i}_sk", exp["sk"]))
        parts.append(c_bytes(f"kat_kg{i}_pk", exp["pk"]))
        parts.append("\n")

    parts.append(
        "typedef struct {\n"
        "  int tc_id;\n"
        "  const uint8_t *sk_seed, *sk_prf, *pk_seed, *sk, *pk;\n"
        "  size_t sk_len, pk_len;\n"
        "} kat_keygen_t;\n\n"
        "static const kat_keygen_t kat_keygen[KAT_KEYGEN_COUNT] = {\n"
    )
    for i, t in enumerate(chosen):
        exp = keygen_expected[t["tcId"]]
        parts.append(
            f"    {{{t['tcId']}, kat_kg{i}_sk_seed, kat_kg{i}_sk_prf, kat_kg{i}_pk_seed,\n"
            f"     kat_kg{i}_sk, kat_kg{i}_pk,\n"
            f"     sizeof(kat_kg{i}_sk), sizeof(kat_kg{i}_pk)}},\n"
        )
    parts.append("};\n\n")

    # --- sigGen, internal interface (slh_sign_internal) ---------------------
    sg_int = pick_group(siggen_prompt, signatureInterface="internal", deterministic=True)
    # --- sigGen, external pure interface (slh_sign with context) ------------
    sg_ext = pick_group(
        siggen_prompt, signatureInterface="external", deterministic=True, preHash="pure"
    )

    for tag, group in (("int", sg_int), ("ext", sg_ext)):
        shortest = sorted(group["tests"], key=lambda t: len(t["message"]))
        for i, t in enumerate(shortest[:SIGN_CASES]):
            exp = siggen_expected[t["tcId"]]
            parts.append(f"/* sigGen tcId {t['tcId']} ({tag}) */\n")
            parts.append(c_bytes(f"kat_sg_{tag}{i}_sk", t["sk"]))
            parts.append(c_bytes(f"kat_sg_{tag}{i}_msg", t["message"]))
            if tag == "ext":
                parts.append(c_bytes(f"kat_sg_{tag}{i}_ctx", t.get("context", "")))
            parts.append(c_bytes(f"kat_sg_{tag}{i}_sig", exp["signature"]))
            parts.append("\n")

    parts.append("// clang-format on\n\n#endif /* KAT_SLHDSA_SHA2_128S_H */\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(parts))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
